version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/event-reward
    depends_on:
      - mongodb

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/event-reward
      - AUTH_BASE_URL=http://auth-service:3001/api/v1/auth
      - EVENT_BASE_URL=http://event-service:3002/api/v1
    depends_on:
      - mongodb
      - auth-service
      - event-service

  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/event-reward
    depends_on:
      - mongodb

volumes:
  mongo-data:


networks:
  default:
    driver: bridge
